(estagio_debugprov) C:\Users\lucas\Desktop\estágio\estagio_debugprov>debugprov program.py
Count - Min:
4
inf
 
Choose a navigation strategy:
[1] - SingleStepping
[2] - TopDown
[3] - HeaviestFirst
[4] - DivideAndQuery
> 1
Do you want to use provenance enhancement?  (y/n) y
How do you want to perform the enhancement?
[1] - Use the last print as criterion
[2] - Use a wrong output as criterion
[3] - Select node as criterion
> 1
Traceback (most recent call last):
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\graphviz\backend.py", line 164, in run
    proc = subprocess.Popen(cmd, startupinfo=get_startupinfo(), **kwargs)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] O sistema não pode encontrar o arquivo especificado
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\main.py", line 8, in main
    ConsoleInterface().run()
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\console_interface.py", line 115, in run
    result_tree = nav.navigate()
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\single_stepping.py", line 8, in navigate
    self.recursive_navigate(self.exec_tree.root_node)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\single_stepping.py", line 16, in recursive_navigate
    self.recursive_navigate(c)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\single_stepping.py", line 16, in recursive_navigate
    self.recursive_navigate(c)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\single_stepping.py", line 17, in recursive_navigate
    self.evaluate(current_node)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\navgiation_strategy.py", line 32, in evaluate
    self._interactive_evaluation(node)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\navgiation_strategy.py", line 56, in _interactive_evaluation
    vis.view_exec_tree(str(id(node)))
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\visualization.py", line 51, in view_exec_tree
    self.graph.view()
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\graphviz\files.py", line 242, in view
    quiet=quiet, quiet_view=quiet_view)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\graphviz\files.py", line 209, in render
    quiet=quiet)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\graphviz\backend.py", line 221, in render
    run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\graphviz\backend.py", line 167, in run
    raise ExecutableNotFound(cmd)
graphviz.backend.ExecutableNotFound: failed to execute ['dot', '-Tpdf', '-O', '2840376317448.gv'], make sure the Graphviz executables are on your systems' PATH
 
(estagio_debugprov) C:\Users\lucas\Desktop\estágio\estagio_debugprov>rd /s x
x, Tem certeza (S/N)? n
 
(estagio_debugprov) C:\Users\lucas\Desktop\estágio\estagio_debugprov>rd /s .noworkflow
.noworkflow, Tem certeza (S/N)? s
 
(estagio_debugprov) C:\Users\lucas\Desktop\estágio\estagio_debugprov>debugprov program.py
Count - Min:
4
inf
 
Choose a navigation strategy:
[1] - SingleStepping
[2] - TopDown
[3] - HeaviestFirst
[4] - DivideAndQuery
> 1
Do you want to use provenance enhancement?  (y/n) y
How do you want to perform the enhancement?
[1] - Use the last print as criterion
[2] - Use a wrong output as criterion
[3] - Select node as criterion
> 2
Tell me which output data is wrong
> pdata
Traceback (most recent call last):
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\main.py", line 8, in main
    ConsoleInterface().run()
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\console_interface.py", line 105, in run
    wrong_data_id = prov.get_wrong_data_evid(wrong_data)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\provenance_enhancement.py", line 59, in get_wrong_data_evid
    raise Exception("Could not find wrong node")
Exception: Could not find wrong node
 
(estagio_debugprov) C:\Users\lucas\Desktop\estágio\estagio_debugprov>debugprov program.py
Traceback (most recent call last):
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\main.py", line 7, in main
    NowInterface().run_script()
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\now_interface.py", line 13, in run_script
    stdout, stderr = proc.communicate()
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\subprocess.py", line 964, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\subprocess.py", line 1296, in _communicate
    self.stdout_thread.join(self._remaining_time(endtime))
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\threading.py", line 1044, in join
    self._wait_for_tstate_lock()
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\threading.py", line 1060, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
 
(estagio_debugprov) C:\Users\lucas\Desktop\estágio\estagio_debugprov>rd /s x
x, Tem certeza (S/N)? n
 
(estagio_debugprov) C:\Users\lucas\Desktop\estágio\estagio_debugprov>rd /s .noworkflow
.noworkflow, Tem certeza (S/N)? s
 
(estagio_debugprov) C:\Users\lucas\Desktop\estágio\estagio_debugprov>debugprov program.py
Count - Min:
4
inf
 
Choose a navigation strategy:
[1] - SingleStepping
[2] - TopDown
[3] - HeaviestFirst
[4] - DivideAndQuery
> 1
Do you want to use provenance enhancement?  (y/n) y
How do you want to perform the enhancement?
[1] - Use the last print as criterion
[2] - Use a wrong output as criterion
[3] - Select node as criterion
> 2
Tell me which output data is wrong
> print_results
Traceback (most recent call last):
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\main.py", line 8, in main
    ConsoleInterface().run()
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\console_interface.py", line 106, in run
    prov.enhance(wrong_data_id)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\provenance_enhancement.py", line 75, in enhance
    nodes_to_visit = self.dependencies[wd]
UnboundLocalError: local variable 'wd' referenced before assignment
 
(estagio_debugprov) C:\Users\lucas\Desktop\estágio\estagio_debugprov>rd /s .noworkflow
.noworkflow, Tem certeza (S/N)? y
.noworkflow, Tem certeza (S/N)? s
 
(estagio_debugprov) C:\Users\lucas\Desktop\estágio\estagio_debugprov>debugorov program.py
'debugorov' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.
 
(estagio_debugprov) C:\Users\lucas\Desktop\estágio\estagio_debugprov>debugprov program.py
Count - Min:
4
inf
 
Choose a navigation strategy:
[1] - SingleStepping
[2] - TopDown
[3] - HeaviestFirst
[4] - DivideAndQuery
> 1
Do you want to use provenance enhancement?  (y/n) y
How do you want to perform the enhancement?
[1] - Use the last print as criterion
[2] - Use a wrong output as criterion
[3] - Select node as criterion
> 3
Traceback (most recent call last):
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\graphviz\backend.py", line 164, in run
    proc = subprocess.Popen(cmd, startupinfo=get_startupinfo(), **kwargs)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] O sistema não pode encontrar o arquivo especificado
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\main.py", line 8, in main
    ConsoleInterface().run()
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\console_interface.py", line 110, in run
    tmp_vis.view_exec_tree('tmp_tree')
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\debugprov-0.0.1-py3.7.egg\debugprov\visualization.py", line 51, in view_exec_tree
    self.graph.view()
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\graphviz\files.py", line 242, in view
    quiet=quiet, quiet_view=quiet_view)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\graphviz\files.py", line 209, in render
    quiet=quiet)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\graphviz\backend.py", line 221, in render
    run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
  File "D:\Users\lucas\anaconda3\envs\estagio_debugprov\lib\site-packages\graphviz\backend.py", line 167, in run
    raise ExecutableNotFound(cmd)
graphviz.backend.ExecutableNotFound: failed to execute ['dot', '-Tpdf', '-O', 'tmp_tree.gv'], make sure the Graphviz executables are on your systems' PATH
 
